name: Releases

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17

      - name: Gradle Build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: assembleRelease

      - name: Generate release tag
        id: version
        run: |
          TAG_NAME=$(git rev-parse --verify --short HEAD)
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Releases
        uses: softprops/action-gh-release@v2
        with:
          body: Bump Version
          tag_name: ${{ steps.version.outputs.TAG_NAME }}
          files: |
            app/build/outputs/apk/release/*.apk
